//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbDevEntities : DbContext
    {
        public dbDevEntities()
            : base("name=dbDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Delete_Customer(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Delete_Customer", idParameter);
        }
    
        public virtual ObjectResult<Get_Customer_Result> Get_Customer(Nullable<int> count)
        {
            var countParameter = count.HasValue ?
                new ObjectParameter("Count", count) :
                new ObjectParameter("Count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Customer_Result>("Get_Customer", countParameter);
        }
    
        public virtual ObjectResult<Get_CustomerbyID_Result> Get_CustomerbyID(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_CustomerbyID_Result>("Get_CustomerbyID", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Set_Customer(string custName, string custEmail)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var custEmailParameter = custEmail != null ?
                new ObjectParameter("CustEmail", custEmail) :
                new ObjectParameter("CustEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Set_Customer", custNameParameter, custEmailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Customer(Nullable<long> id, string custName, string custEmail)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var custEmailParameter = custEmail != null ?
                new ObjectParameter("CustEmail", custEmail) :
                new ObjectParameter("CustEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Customer", idParameter, custNameParameter, custEmailParameter);
        }
    }
}
